// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyHzEb9KpnDA70Y_RGfVqbbmKga9ap5yo',
    appId: '1:969803822905:web:2d6a481a7fa6685fd49ae8',
    messagingSenderId: '969803822905',
    projectId: 'mealmingle-4c218',
    authDomain: 'mealmingle-4c218.firebaseapp.com',
    storageBucket: 'mealmingle-4c218.appspot.com',
    measurementId: 'G-VPHC262S8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn9-LCemmqKizpjhGhUKTZSTX44SGHPg8',
    appId: '1:969803822905:android:40dd694ff051e35ad49ae8',
    messagingSenderId: '969803822905',
    projectId: 'mealmingle-4c218',
    storageBucket: 'mealmingle-4c218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhGBDZf6-MpcbFUYiXmiv0Sp1LHr8T_Lg',
    appId: '1:969803822905:ios:70f850703fd5ae88d49ae8',
    messagingSenderId: '969803822905',
    projectId: 'mealmingle-4c218',
    storageBucket: 'mealmingle-4c218.appspot.com',
    iosBundleId: 'com.example.mealmingle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhGBDZf6-MpcbFUYiXmiv0Sp1LHr8T_Lg',
    appId: '1:969803822905:ios:70f850703fd5ae88d49ae8',
    messagingSenderId: '969803822905',
    projectId: 'mealmingle-4c218',
    storageBucket: 'mealmingle-4c218.appspot.com',
    iosBundleId: 'com.example.mealmingle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyHzEb9KpnDA70Y_RGfVqbbmKga9ap5yo',
    appId: '1:969803822905:web:3ae090bf50cc5963d49ae8',
    messagingSenderId: '969803822905',
    projectId: 'mealmingle-4c218',
    authDomain: 'mealmingle-4c218.firebaseapp.com',
    storageBucket: 'mealmingle-4c218.appspot.com',
    measurementId: 'G-QGDY7VHM44',
  );
}
